# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_run:
    workflows:
      - Python package
    branches:
      - dev
      - main
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Sets env vars for dev
      run: |
        echo "ENV=dev" >> $GITHUB_ENV
        echo "PYPI_TOKEN=${{ secrets.TEST_PYPI_API_TOKEN }}" >> $GITHUB_ENV
        echo "PYPI_URL=https://test.pypi.org/legacy/" >> $GITHUB_ENV
      if: startsWith(github.ref_name, 'dev')

    - name: Sets env vars for main
      run: |
        echo "ENV=main" >> $GITHUB_ENV
        echo "PYPI_TOKEN=${{ secrets.PYPI_API_TOKEN }}" >> $GITHUB_ENV
        echo "PYPI_URL=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
      if: startsWith(github.ref_name, 'main')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ env.PYPI_TOKEN }}
        repository_url: ${{ env.PYPI_URL }}
